name: CI

on:
  push:

jobs:
  static:
    name: Static formatters and analyzers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cmake
        run: |
          mkdir build && cd build
          make ..
          make build .
      - name: clang-format
        run: |
          echo "apt-get install clang-format log"
          sudo apt-get install -y clang-format
          echo "clang-format log"
          clang-format --dry-run -Werror project/*.cpp project/*.h
